[package]
name = "wrap_cspr"
version = "0.1.0"
edition = "2021"
authors = ["Pantheon"]

[[bin]]
name = "wrap_cspr"
path = "src/main.rs"
test = false
doctest = false
bench = false
doc = false

[dependencies]
casper-contract = { version = "5.0.1", default-features = false, features = ["no-std-helpers"] }
casper-types = { version = "6.1.0", default-features = false }


[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
